### ISSUE TITLE
min_snr_gamma not defined

### ISSUE THREAD

**Issue by without-ordinary** [ArgentVASIMR/FD-lora#2]
Not sure of the intent since it checks for greater than zero, instead of just true/false, and then uses a fixed value of 5.

https://github.com/ArgentVASIMR/FD-lora/blob/main/use-me.ps1#L146

**Comment by ArgentVASIMR** [comment]
Fixed.
https://github.com/ArgentVASIMR/FD-lora/blob/main/use-me.ps1#L237
