### ISSUE TITLE
Exception is thrown if prompt file is provided

### ISSUE THREAD

**Issue by renfald** [ArgentVASIMR/FD-lora#4]
```shell
# Directories
    if ($prompts -ne "") {
        $extra += "--sample_prompts=$prompts", "--sample_sampler=euler", "--sample_every_n_steps=$save_nth_step"
    }
``` 

    
 --sample_every_n_steps is added to the $extra variable before being assigned a value. When the script runs it will thrown an exception because --sample_every_n_steps requires an integer.
 
 A quick fix for this would be to simply move it under this block:
 ```shell
 # Steps
    $total_grad_acc = $batch_size*$grad_acc_step
    $base_steps = [int]([Math]::Round($base_steps / $total_grad_acc))
    if ($save_amount -gt 0){
        $save_nth_step = [int]([Math]::Round($base_steps / $save_amount))
        $extra += "--save_every_n_steps=$save_nth_step"
    }
``` 
There may still be an edge case where it would break if $save_amount is 0, but I don't know why someone would do that.

**Comment by ArgentVASIMR** [comment]
Sorry for taking so long on this, finally got around to it.
https://github.com/ArgentVASIMR/FD-LoRA/commit/529241e8b73298c6a67b33867ae5f21b05184300
